In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
data = pd.read_csv('D:/Ai course/2.MachineLearning/insurance_pre.csv')
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(data,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [5]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error','absolute_error','poisson','friedman_mse','mae'],
           'max_features':['auto','log2'],'n_estimators':[50,100,1000]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,verbose=3,n_jobs=-1,refit=True)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson', 'friedman_mse', 'mae'],
                         'max_features': ['auto', 'log2'],
                         'n_estimators': [50, 100, 1000]},
             verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions=grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print('The R_score value of best parameter{} is:'.format(grid.best_params_),r_score)

The R_score value of best parameter{'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 1000} is: 0.8738820343482823

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.213636,0.008039,0.012568,1.196981e-03,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",0.802363,0.753771,0.829671,0.799906,0.755145,0.788171,0.029446,20
1,0.388576,0.002999,0.021744,1.465383e-03,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.803603,0.751967,0.836994,0.809171,0.763366,0.793020,0.031213,13
2,3.859833,0.027263,0.189502,1.509967e-02,squared_error,auto,1000,"{'criterion': 'squared_error', 'max_features':...",0.803282,0.751819,0.835135,0.808887,0.765351,0.792895,0.030311,15
3,0.166361,0.002778,0.011769,3.988268e-04,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.804580,0.770641,0.831911,0.824308,0.762227,0.798733,0.027968,9
4,0.316166,0.002821,0.020148,7.464422e-04,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.809977,0.771908,0.834202,0.825312,0.764456,0.801171,0.028127,6
5,3.095845,0.028210,0.178730,5.293029e-03,squared_error,log2,1000,"{'criterion': 'squared_error', 'max_features':...",0.807344,0.773431,0.837252,0.834035,0.762543,0.802921,0.030549,2
6,0.829414,0.033442,0.010772,7.462640e-04,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",0.786223,0.766441,0.807000,0.797510,0.757768,0.782988,0.018481,24
7,1.645266,0.067035,0.018951,8.916436e-04,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.790075,0.767591,0.820972,0.805973,0.759618,0.788846,0.022948,18
8,16.359313,0.572955,0.168756,3.420096e-03,absolute_error,auto,1000,"{'criterion': 'absolute_error', 'max_features'...",0.785492,0.770301,0.819133,0.803617,0.759423,0.787593,0.021673,21
9,0.521825,0.031251,0.010573,4.888114e-04,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.807398,0.764654,0.837560,0.821900,0.751782,0.796659,0.033057,11
10,1.034873,0.067606,0.018552,4.887922e-04,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.807271,0.768000,0.839539,0.825388,0.761669,0.800373,0.030833,8
11,10.304859,0.556681,0.172347,5.930650e-03,absolute_error,log2,1000,"{'criterion': 'absolute_error', 'max_features'...",0.803443,0.774687,0.839382,0.827738,0.762626,0.801575,0.029521,5
12,0.287841,0.002863,0.010972,4.422006e-07,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",0.739517,0.725321,0.797537,0.786200,0.745394,0.758794,0.028013,27
13,0.574686,0.005514,0.019748,3.986121e-04,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.751984,0.723297,0.803314,0.785521,0.751647,0.763153,0.028138,26
14,5.761625,0.032797,0.178330,6.507160e-03,poisson,auto,1000,"{'criterion': 'poisson', 'max_features': 'auto...",0.748272,0.724876,0.805437,0.787333,0.751786,0.763541,0.028940,25
15,0.200072,0.001621,0.010972,6.308265e-04,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.756607,0.708531,0.809585,0.786771,0.698673,0.752033,0.043080,30
16,0.394959,0.001784,0.019150,3.989225e-04,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.761443,0.699564,0.816127,0.793665,0.699674,0.754095,0.047756,29
17,3.997471,0.024778,0.178930,4.117066e-03,poisson,log2,1000,"{'criterion': 'poisson', 'max_features': 'log2...",0.762852,0.711483,0.818395,0.794575,0.705743,0.758610,0.044501,28
18,0.198078,0.003545,0.011371,4.884614e-04,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.807284,0.746069,0.839397,0.797157,0.767783,0.791538,0.032254,16
19,0.386183,0.001715,0.020347,7.978205e-04,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.804136,0.749138,0.836693,0.806301,0.759652,0.791184,0.032340,17
20,3.936631,0.063985,0.189302,1.332782e-02,friedman_mse,auto,1000,"{'criterion': 'friedman_mse', 'max_features': ...",0.804871,0.751113,0.836435,0.806313,0.766100,0.792966,0.030604,14
21,0.200076,0.039700,0.014559,5.226089e-03,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.805744,0.763269,0.831286,0.820843,0.760658,0.796360,0.029247,12
22,0.349479,0.022749,0.021543,2.721159e-03,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.798239,0.773593,0.841464,0.833489,0.766561,0.802669,0.030409,4
23,3.129357,0.028634,0.175339,5.404387e-03,friedman_mse,log2,1000,"{'criterion': 'friedman_mse', 'max_features': ...",0.810015,0.770702,0.838382,0.833782,0.762814,0.803139,0.031326,1
24,0.830811,0.031897,0.011571,4.888697e-04,mae,auto,50,"{'criterion': 'mae', 'max_features': 'auto', '...",0.790865,0.768659,0.812155,0.800659,0.757756,0.786019,0.020105,23
25,1.791484,0.037840,0.026328,6.290422e-03,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.782914,0.770329,0.816284,0.810029,0.757561,0.787423,0.022575,22
26,16.869399,0.600698,0.199274,2.428698e-02,mae,auto,1000,"{'criterion': 'mae', 'max_features': 'auto', '...",0.786144,0.769451,0.819623,0.807648,0.758937,0.788361,0.022705,19
27,0.533388,0.042471,0.010573,4.880135e-04,mae,log2,50,"{'criterion': 'mae', 'max_features': 'log2', '...",0.792948,0.773360,0.835949,0.829111,0.758528,0.797979,0.030327,10
28,1.062588,0.060036,0.020148,2.918172e-03,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.800047,0.772244,0.839531,0.826431,0.764710,0.800592,0.029241,7
29,9.624543,2.025405,0.162172,3.397156e-02,mae,log2,1000,"{'criterion': 'mae', 'max_features': 'log2', '...",0.803836,0.775721,0.840099,0.830638,0.763342,0.802727,0.029858,3